version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      MYSQL_DATABASE: banco-de-dados
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql